# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build-backend:
    desc: build backend
    cmds:
      - go build -o ./tmp/backend ./src/backend/main.go
  run-backend:
    dotenv: [".env"]
    dir: ./src/backend/
    cmds:
      - go run main.go
  run-frontend:
    dotenv: [".env"]
    dir: ./src/frontend/
    cmds:
      - npm run dev
  up:
    dir: .
    cmds:
      - docker compose up
  down:
    dir: .
    cmds:
      - docker compose down
  prd-up:
    dotenv: ["src/backend/.env", "src/frontend/.env"]
    dir: .
    cmds:
      - docker compose -f docker-compose.b.yaml up --build -d
  prd-down:
    dir: .
    cmds:
      - docker compose -f docker-compose.b.yaml down
